export const COMPLAINT_FETCH_REQUEST = 'COMPLAINT_FETCH_REQUEST'
export const COMPLAINT_FETCH_SUCCESS = 'COMPLAINT_FETCH_SUCCESS'
export const COMPLAINT_FETCH_FAIL = 'COMPLAINT_FETCH_FAIL'
export const COMPLAINT_FETCH_RESET = 'COMPLAINT_FETCH_RESET'

export const COMPLAINT_REPLY_REQUEST = 'COMPLAINT_REPLY_REQUEST'
export const COMPLAINT_REPLY_SUCCESS = 'COMPLAINT_REPLY_SUCCESS'
export const COMPLAINT_REPLY_FAIL = 'COMPLAINT_REPLY_FAIL'
export const COMPLAINT_REPLY_RESET = 'COMPLAINT_REPLY_RESET'

export const COMPLAINT_DELETE_REQUEST = 'COMPLAINT_DELETE_REQUEST'
export const COMPLAINT_DELETE_SUCCESS = 'COMPLAINT_DELETE_SUCCESS'
export const COMPLAINT_DELETE_FAIL = 'COMPLAINT_DELETE_FAIL'
export const COMPLAINT_DELETE_RESET = 'COMPLAINT_DELETE_RESET'

export const COMPLAINT_ADD_REQUEST = 'COMPLAINT_ADD_REQUEST'
export const COMPLAINT_ADD_SUCCESS = 'COMPLAINT_ADD_SUCCESS'
export const COMPLAINT_ADD_FAIL = 'COMPLAINT_ADD_FAIL'
export const COMPLAINT_ADD_RESET = 'COMPLAINT_ADD_RESET'
