export const DASHBOARD_FETCH_REQUEST = 'DASHBOARD_FETCH_REQUEST'
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD_FETCH_SUCCESS'
export const DASHBOARD_FETCH_FAIL = 'DASHBOARD_FETCH_FAIL'
export const DASHBOARD_FETCH_RESET = 'DASHBOARD_FETCH_RESET'

export const SECURITY_FETCH_REQUEST = 'SECURITY_FETCH_REQUEST'
export const SECURITY_FETCH_SUCCESS = 'SECURITY_FETCH_SUCCESS'
export const SECURITY_FETCH_FAIL = 'SECURITY_FETCH_FAIL'
export const SECURITY_FETCH_RESET = 'SECURITY_FETCH_RESET'

export const VISITORS_FETCH_REQUEST = 'VISITORS_FETCH_REQUEST'
export const VISITORS_FETCH_SUCCESS = 'VISITORS_FETCH_SUCCESS'
export const VISITORS_FETCH_FAIL = 'VISITORS_FETCH_FAIL'
export const VISITORS_FETCH_RESET = 'VISITORS_FETCH_RESET'

export const WINGS_FETCH_REQUEST = 'WINGS_FETCH_REQUEST'
export const WINGS_FETCH_SUCCESS = 'WINGS_FETCH_SUCCESS'
export const WINGS_FETCH_FAIL = 'WINGS_FETCH_FAIL'
export const WINGS_FETCH_RESET = 'WINGS_FETCH_RESET'