export const DOCUMENT_FETCH_REQUEST = 'DOCUMENT_FETCH_REQUEST'
export const DOCUMENT_FETCH_SUCCESS = 'DOCUMENT_FETCH_SUCCESS'
export const DOCUMENT_FETCH_FAIL = 'DOCUMENT_FETCH_FAIL'
export const DOCUMENT_FETCH_RESET = 'DOCUMENT_FETCH_RESET'

export const DOCUMENT_DOWNLOAD_REQUEST = 'DOCUMENT_DOWNLOAD_REQUEST'
export const DOCUMENT_DOWNLOAD_SUCCESS = 'DOCUMENT_DOWNLOAD_SUCCESS'
export const DOCUMENT_DOWNLOAD_FAIL = 'DOCUMENT_DOWNLOAD_FAIL'
export const DOCUMENT_DOWNLOAD_RESET = 'DOCUMENT_DOWNLOAD_RESET'

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST'
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS'
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL'
export const DOCUMENT_DELETE_RESET = 'DOCUMENT_DELETE_RESET'

export const DOCUMENT_UPLOAD_REQUEST = 'DOCUMENT_UPLOAD_REQUEST'
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS'
export const DOCUMENT_UPLOAD_FAIL = 'DOCUMENT_UPLOAD_FAIL'
export const DOCUMENT_UPLOAD_RESET = 'DOCUMENT_UPLOAD_RESET'
