export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST'
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS'
export const ADD_FEEDBACK_FAIL = 'ADD_FEEDBACK_FAIL'

export const FETCH_FEEDBACK_REQUEST = 'FETCH_FEEDBACK_REQUEST'
export const FETCH_FEEDBACK_SUCCESS = 'FETCH_FEEDBACK_SUCCESS'
export const FETCH_FEEDBACK_FAIL = 'FETCH_FEEDBACK_FAIL'
