export const FLAT_REQUEST = 'FLAT_REQUEST'
export const FLAT_SUCCESS = 'FLAT_SUCCESS'
export const FLAT_FAIL = 'FLAT_FAIL'
export const FLAT_RESET = 'FLAT_RESET'

export const FLAT_LIST_REQUEST = 'FLAT_LIST_REQUEST'
export const FLAT_LIST_SUCCESS = 'FLAT_LIST_SUCCESS'
export const FLAT_LIST_FAIL = 'FLAT_LIST_FAIL'
export const FLAT_LIST_RESET = 'FLAT_LIST_RESET'

export const FLAT_DELETE_REQUEST = 'FLAT_DELETE_REQUEST'
export const FLAT_DELETE_SUCCESS = 'FLAT_DELETE_SUCCESS'
export const FLAT_DELETE_FAIL = 'FLAT_DELETE_FAIL'
export const FLAT_DELETE_RESET = 'FLAT_DELETE_RESET'