export const NOTICE_FETCH_REQUEST = 'NOTICE_FETCH_REQUEST'
export const NOTICE_FETCH_SUCCESS = 'NOTICE_FETCH_SUCCESS'
export const NOTICE_FETCH_FAIL = 'NOTICE_FETCH_FAIL'
export const NOTICE_FETCH_RESET = 'NOTICE_FETCH_RESET'

export const NOTICE_ADD_REQUEST = 'NOTICE_ADD_REQUEST'
export const NOTICE_ADD_SUCCESS = 'NOTICE_ADD_SUCCESS'
export const NOTICE_ADD_FAIL = 'NOTICE_ADD_FAIL'
export const NOTICE_ADD_RESET = 'NOTICE_ADD_RESET'

export const NOTICE_DELETE_REQUEST = 'NOTICE_DELETE_REQUEST'
export const NOTICE_DELETE_SUCCESS = 'NOTICE_DELETE_SUCCESS'
export const NOTICE_DELETE_FAIL = 'NOTICE_DELETE_FAIL'
export const NOTICE_DELETE_RESET = 'NOTICE_DELETE_RESET'
