export const RESIDENT_FETCH_REQUEST = 'RESIDENT_FETCH_REQUEST'
export const RESIDENT_FETCH_SUCCESS = 'RESIDENT_FETCH_SUCCESS'
export const RESIDENT_FETCH_FAIL = 'RESIDENT_FETCH_FAIL'
export const RESIDENT_FETCH_RESET = 'RESIDENT_FETCH_RESET'

export const RESIDENT_ADD_REQUEST = 'RESIDENT_ADD_REQUEST'
export const RESIDENT_ADD_SUCCESS = 'RESIDENT_ADD_SUCCESS'
export const RESIDENT_ADD_FAIL = 'RESIDENT_ADD_FAIL'
export const RESIDENT_ADD_RESET = 'RESIDENT_ADD_RESET'

export const RESIDENT_DELETE_REQUEST = 'RESIDENT_DELETE_REQUEST'
export const RESIDENT_DELETE_SUCCESS = 'RESIDENT_DELETE_SUCCESS'
export const RESIDENT_DELETE_FAIL = 'RESIDENT_DELETE_FAIL'
export const RESIDENT_DELETE_RESET = 'RESIDENT_DELETE_RESET'
