export const SECURITY_FETCH_REQUEST = 'SECURITY_FETCH_REQUEST'
export const SECURITY_FETCH_SUCCESS = 'SECURITY_FETCH_SUCCESS'
export const SECURITY_FETCH_FAIL = 'SECURITY_FETCH_FAIL'
export const SECURITY_FETCH_RESET = 'SECURITY_FETCH_RESET'

export const SECURITY_ADD_REQUEST = 'SECURITY_ADD_REQUEST'
export const SECURITY_ADD_SUCCESS = 'SECURITY_ADD_SUCCESS'
export const SECURITY_ADD_FAIL = 'SECURITY_ADD_FAIL'
export const SECURITY_ADD_RESET = 'SECURITY_ADD_RESET'
