export const SOCIETY_FETCH_REQUEST = 'SOCIETY_FETCH_REQUEST'
export const SOCIETY_FETCH_SUCCESS = 'SOCIETY_FETCH_SUCCESS'
export const SOCIETY_FETCH_FAIL = 'SOCIETY_FETCH_FAIL'
export const SOCIETY_FETCH_RESET = 'SOCIETY_FETCH_RESET'

export const SOCIETY_ADD_REQUEST = 'SOCIETY_ADD_REQUEST'
export const SOCIETY_ADD_SUCCESS = 'SOCIETY_ADD_SUCCESS'
export const SOCIETY_ADD_FAIL = 'SOCIETY_ADD_FAIL'
export const SOCIETY_ADD_RESET = 'SOCIETY_ADD_RESET'
