export const VISITOR_ENTER_REQUEST = 'VISITOR_ENTER_REQUEST'
export const VISITOR_ENTER_SUCCESS = 'VISITOR_ENTER_SUCCESS'
export const VISITOR_ENTER_FAIL = 'VISITOR_ENTER_FAIL'

export const VISITOR_EXIT_REQUEST = 'VISITOR_EXIT_REQUEST'
export const VISITOR_EXIT_SUCCESS = 'VISITOR_EXIT_SUCCESS'
export const VISITOR_EXIT_FAIL = 'VISITOR_EXIT_FAIL'

export const VISITOR_PARKING_REQUEST = 'VISITOR_PARKING_REQUEST'
export const VISITOR_PARKING_SUCCESS = 'VISITOR_PARKING_SUCCESS'
export const VISITOR_PARKING_FAIL = 'VISITOR_PARKING_FAIL'

export const RESIDENT_PARKING_REQUEST = 'RESIDENT_PARKING_REQUEST'
export const RESIDENT_PARKING_SUCCESS = 'RESIDENT_PARKING_SUCCESS'
export const RESIDENT_PARKING_FAIL = 'RESIDENT_PARKING_FAIL'