export const VISITOR_FETCH_REQUEST = 'VISITOR_FETCH_REQUEST'
export const VISITOR_FETCH_SUCCESS = 'VISITOR_FETCH_SUCCESS'
export const VISITOR_FETCH_FAIL = 'VISITOR_FETCH_FAIL'
export const VISITOR_FETCH_RESET = 'VISITOR_FETCH_RESET'

export const VISITOR_ADD_REQUEST = 'VISITOR_ADD_REQUEST'
export const VISITOR_ADD_SUCCESS = 'VISITOR_ADD_SUCCESS'
export const VISITOR_ADD_FAIL = 'VISITOR_ADD_FAIL'
export const VISITOR_ADD_RESET = 'VISITOR_ADD_RESET'

export const VISITOR_UPDATE_REQUEST = 'VISITOR_UPDATE_REQUEST'
export const VISITOR_UPDATE_SUCCESS = 'VISITOR_UPDATE_SUCCESS'
export const VISITOR_UPDATE_FAIL = 'VISITOR_UPDATE_FAIL'
export const VISITOR_UPDATE_RESET = 'VISITOR_UPDATE_RESET'
